project:
  type: website
  output-dir: docs

website:
  title: "Kristin Privitera-Johnson"
  navbar:
    right:
      - href: blog.qmd
        text: News
      - href: notebook.qmd
        text: Research Notebook
      - href: https://kpjohnson.github.io/ESM254/
        text: ESM 254
      - icon: github
        href: https://github.com/kpjohnson
      - icon: twitter
        href: https://twitter.com/kristinpjohnson
  cookie-consent:
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-1S0WLJGSQ5"
    anonymize-ip: true
format:
  html:
    theme: sandstone
    css: styles.css



