project:
  type: website
  output-dir: docs

website:
  title: "Kristin Privitera-Johnson"
  navbar:
    right:
      - blog.qmd
      - notebook.qmd
      - icon: github
        href: https://github.com/kpjohnson
      - icon: twitter
        href: https://twitter.com/kristinpjohnson
format:
  html:
    theme: sandstone
    css: styles.css



