project:
  type: website
  output-dir: docss

website:
  title: "Kristin Privitera-Johnson"
  navbar:
    right:
      - href: blog.qmd
        text: News
      - href: notebook.qmd
        text: Research Notebook
      - href: https://kpjohnson.github.io/ESM254/
        text: ESM 254
      - icon: github
        href: https://github.com/kpjohnson
      - icon: twitter
        href: https://twitter.com/kristinpjohnson
format:
  html:
    theme: sandstone
    css: styles.css



