---
title: "April 2023 Goals"
author: "Kristin Privitera-Johnson"
date: "2023-04-01"
categories: ["SAFS", "monthly goals", "daily snapshots"]
format:
  html:
    toc: true
---

# Monthly Goals
- Run simulations for Ch. 1 natural mortality experiment using the status quo HCR and the phase-in HCR
- Prepare a presentation for May 2nd UW SAFS Think Tank Workshop
- Conduct a brief literature review re: semi-structured interviews (for Ch. 4)

# Daily Snapshots

## 17 April 2023
- continued troubleshooting the phase-in HCR code for Ch. 1, there's something up with the for loops
- met with adviser to check-in + diagnose issues with phase-in HCR code

## 16 April 2023
- continued troubleshooting the phase-in HCR code for Ch. 1, there's something up with the for loops

## 12 April 2023
- continued troubleshooting the phase-in HCR code for Ch. 1, there's something up with the for loops

## 3 April 2023
- continued troubleshooting the phase-in HCR code for Ch. 1, there's something up with the for loops
- it's the first week of teaching at UCSB