---
title: "March 2023 Goals"
author: "Kristin Privitera-Johnson"
date: "2023-02-27"
categories: ["SAFS", "monthly goals", "daily snapshots"]
format:
  html:
    toc: true
---

# Monthly Goals
- Review the following sections of the Punt Student reading list:
    - Stock Assessment
    - Ecology and Ecosystems (compare to TEE quals reading list)
    - Fisheries Management and Policy
- Prepare the final draft of the Proposal Presentation for my General Exam
- Run simulations for Ch. 1 natural mortality experiment using the status quo HCR and the phase-in HCR

# Daily Snapshots

## 13 March 2023
- finished Ch. 1 section of final draft slide deck
- produced best available plots from Ch. 1 for slide deck
- skimmed wiedenmann et al. paper and make checklist for Ch. 2 plots
- started final draft of Ch. 2 section of slide deck

## 11 March 2023
- drafted final prioritization list for exam prep
  
## 8 March 2023
- final draft of proposal presentation for General Exam
  - Chapter 1 components filled in (50%)

## 7 March 2023
- started building the final draft of proposal presentation for General Exam
  - new outline produced
  - introduction components filled in

## 1 March - 6 March 2023
- some pretty serious burn out
- watched Ian Stewart's NOAA Monster Jam seminar about the use of ensemble modelling at IPHC for Ch. 3